# Generated by Django 5.0.4 on 2024-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistsRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.TextField(blank=True, null=True)),
                ('certification_category', models.CharField(blank=True, max_length=150, null=True)),
                ('category_assignment_order', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'specialists_registry',
                'managed': False,
            },
        ),
    ]
